window.__ENV__ = {
  FIREBASE_API_KEY: 'AIzaSyAlOrxlLbZV-ZzxDcFrretv2dycKtF4dyM',
  FIREBASE_AUTH_DOMAIN: 'healling-forest.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'healling-forest',
  FIREBASE_STORAGE_BUCKET: 'healling-forest.firebasestorage.app',
  FIREBASE_MESSAGING_SENDER_ID: '657330224656',
  FIREBASE_APP_ID: '1:657330224656:web:e8c9b0f2a6d5c3e4f5a6b7',

  TWILIO_ACCOUNT_SID: '',
  TWILIO_AUTH_TOKEN: '',
  TWILIO_WHATSAPP_NUMBER: '+14155238886',

  EMAILJS_SERVICE_ID: 'YOUR_SERVICE_ID',
  EMAILJS_TEMPLATE_ID: 'YOUR_TEMPLATE_ID',
  EMAILJS_PUBLIC_KEY: 'YOUR_PUBLIC_KEY',

  SIIGO_API_KEY: '',
  SIIGO_COMPANY_ID: ''
};
